version: '3.5'
services:
    db:
        container_name: db
        image: mysql:5.7.36
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_USER: jwtengine
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: jwtengine
        volumes:
            - "./.docker/mysql:/var/lib/mysql"

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        depends_on:
            - "db"
        ports:
            - 8080:80

networks:
    default:
        external:
            name: development